PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__new_settings` (
	`id` integer PRIMARY KEY NOT NULL,
	`timezone` text DEFAULT 'Europe/Vienna' NOT NULL,
	`day_start` text DEFAULT '06:00' NOT NULL,
	`day_end` text DEFAULT '18:00' NOT NULL,
	`buffer_min` integer DEFAULT 15 NOT NULL,
	`max_focus_block_min` integer DEFAULT 60 NOT NULL,
	`min_block_min` integer DEFAULT 30 NOT NULL,
	`lunch_start` text DEFAULT '12:00' NOT NULL,
	`lunch_min` integer DEFAULT 30 NOT NULL,
	`default_window_id` integer,
	`target_calendar_id` text,
	`calendar_start` text DEFAULT '05:00' NOT NULL,
	`calendar_end` text DEFAULT '00:00' NOT NULL,
	`calendar_view` text DEFAULT 'week' NOT NULL,
	`calendar_filters` text DEFAULT '{}' NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')) NOT NULL
);
--> statement-breakpoint
INSERT INTO `__new_settings`("id", "timezone", "day_start", "day_end", "buffer_min", "max_focus_block_min", "min_block_min", "lunch_start", "lunch_min", "default_window_id", "target_calendar_id", "calendar_start", "calendar_end", "calendar_view", "calendar_filters", "updated_at") SELECT "id", "timezone", "day_start", "day_end", "buffer_min", "max_focus_block_min", "min_block_min", "lunch_start", "lunch_min", "default_window_id", "target_calendar_id", "calendar_start", "calendar_end", "calendar_view", "calendar_filters", "updated_at" FROM `settings`;--> statement-breakpoint
DROP TABLE `settings`;--> statement-breakpoint
ALTER TABLE `__new_settings` RENAME TO `settings`;--> statement-breakpoint
PRAGMA foreign_keys=ON;--> statement-breakpoint
ALTER TABLE `time_windows` ADD `color` text;--> statement-breakpoint
-- Hand-written data steps (not generated by drizzle-kit) ------------------------
-- The Calendar now opens in Week. A calendar still on the old default (Today) follows;
-- any other view someone chose in Settings is kept.
UPDATE `settings` SET `calendar_view` = 'week' WHERE `calendar_view` = 'day';
