CREATE TABLE `block_segments` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`block_id` integer NOT NULL,
	`task_id` integer NOT NULL,
	`minutes` integer NOT NULL,
	`sort_order` integer DEFAULT 0 NOT NULL,
	`done_at` text
);
--> statement-breakpoint
CREATE INDEX `block_segments_block_idx` ON `block_segments` (`block_id`);--> statement-breakpoint
CREATE INDEX `block_segments_task_idx` ON `block_segments` (`task_id`);--> statement-breakpoint
CREATE TABLE `time_windows` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`name` text NOT NULL,
	`start_time` text NOT NULL,
	`end_time` text NOT NULL,
	`weekdays` text DEFAULT '1,2,3,4,5' NOT NULL,
	`sort_order` integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
DROP INDEX `blocks_task_idx`;--> statement-breakpoint
ALTER TABLE `blocks` ADD `window_id` integer;--> statement-breakpoint
PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__new_settings` (
	`id` integer PRIMARY KEY NOT NULL,
	`timezone` text DEFAULT 'Europe/Vienna' NOT NULL,
	`day_start` text DEFAULT '06:00' NOT NULL,
	`day_end` text DEFAULT '18:00' NOT NULL,
	`buffer_min` integer DEFAULT 15 NOT NULL,
	`max_focus_block_min` integer DEFAULT 60 NOT NULL,
	`min_block_min` integer DEFAULT 30 NOT NULL,
	`lunch_start` text DEFAULT '12:00' NOT NULL,
	`lunch_min` integer DEFAULT 30 NOT NULL,
	`deep_work_before` text DEFAULT '12:00' NOT NULL,
	`default_window_id` integer,
	`target_calendar_id` text,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')) NOT NULL
);
--> statement-breakpoint
INSERT INTO `__new_settings`("id", "timezone", "day_start", "day_end", "buffer_min", "max_focus_block_min", "min_block_min", "lunch_start", "lunch_min", "deep_work_before", "target_calendar_id", "updated_at") SELECT "id", "timezone", "day_start", "day_end", "buffer_min", "max_focus_block_min", "min_block_min", "lunch_start", "lunch_min", "deep_work_before", "target_calendar_id", "updated_at" FROM `settings`;--> statement-breakpoint
DROP TABLE `settings`;--> statement-breakpoint
ALTER TABLE `__new_settings` RENAME TO `settings`;--> statement-breakpoint
PRAGMA foreign_keys=ON;--> statement-breakpoint
ALTER TABLE `horizons` ADD `window_id` integer;--> statement-breakpoint
ALTER TABLE `tasks` ADD `window_id` integer;;--> statement-breakpoint
-- Hand-written data steps (not generated by drizzle-kit) ------------------------
-- Seed the two windows from the v0.2 brief: learning before lunch, work after.
INSERT INTO `time_windows` (`name`, `start_time`, `end_time`, `weekdays`, `sort_order`) VALUES ('Learning', '10:30', '14:00', '1,2,3,4,5', 0);--> statement-breakpoint
INSERT INTO `time_windows` (`name`, `start_time`, `end_time`, `weekdays`, `sort_order`) VALUES ('Work', '14:00', '17:30', '1,2,3,4,5', 1);--> statement-breakpoint
-- Blocks become 30-60 min calendar windows; unassigned work goes to Work.
UPDATE `settings` SET `max_focus_block_min` = 60, `default_window_id` = (SELECT `id` FROM `time_windows` WHERE `name` = 'Work');--> statement-breakpoint
-- Every existing block becomes a single-segment block, so nothing planned is lost
-- when 0002 drops blocks.task_id.
INSERT INTO `block_segments` (`block_id`, `task_id`, `minutes`, `sort_order`, `done_at`)
  SELECT `id`, `task_id`, CAST(ROUND((julianday(`ends_at`) - julianday(`starts_at`)) * 1440) AS INTEGER), 0,
         CASE WHEN `state` = 'done' THEN `updated_at` END
  FROM `blocks`;--> statement-breakpoint
-- Tasks now keep their sequence within a priority; existing ones keep creation order.
UPDATE `tasks` SET `sort_order` = `id` WHERE `sort_order` = 0;
