// Generated by packages/core/scripts/bundle-migrations.mjs from packages/core/drizzle — do not edit.
// Regenerate with `npm run db:generate` (or `node packages/core/scripts/bundle-migrations.mjs`).

export interface Migration {
  name: string;
  statements: readonly string[];
}

export const MIGRATIONS: readonly Migration[] = [
  {
    name: "0000_daily_slapstick.sql",
    statements: [
      "CREATE TABLE `blocks` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`task_id` integer NOT NULL,\n\t`date` text NOT NULL,\n\t`starts_at` text NOT NULL,\n\t`ends_at` text NOT NULL,\n\t`google_event_id` text,\n\t`state` text DEFAULT 'draft' NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')) NOT NULL\n);",
      "CREATE INDEX `blocks_date_idx` ON `blocks` (`date`,`state`);",
      "CREATE INDEX `blocks_task_idx` ON `blocks` (`task_id`);",
      "CREATE TABLE `horizons` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`level` text NOT NULL,\n\t`title` text NOT NULL,\n\t`description` text,\n\t`parent_id` integer,\n\t`period_start` text NOT NULL,\n\t`period_end` text NOT NULL,\n\t`status` text DEFAULT 'active' NOT NULL,\n\t`sort_order` integer DEFAULT 0 NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')) NOT NULL\n);",
      "CREATE INDEX `horizons_level_period_idx` ON `horizons` (`level`,`period_start`);",
      "CREATE INDEX `horizons_parent_idx` ON `horizons` (`parent_id`);",
      "CREATE TABLE `ritual_log` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`kind` text NOT NULL,\n\t`for_period` text NOT NULL,\n\t`completed_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')) NOT NULL\n);",
      "CREATE UNIQUE INDEX `ritual_log_kind_period_idx` ON `ritual_log` (`kind`,`for_period`);",
      "CREATE TABLE `settings` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`timezone` text DEFAULT 'Europe/Vienna' NOT NULL,\n\t`day_start` text DEFAULT '06:00' NOT NULL,\n\t`day_end` text DEFAULT '18:00' NOT NULL,\n\t`buffer_min` integer DEFAULT 15 NOT NULL,\n\t`max_focus_block_min` integer DEFAULT 90 NOT NULL,\n\t`min_block_min` integer DEFAULT 30 NOT NULL,\n\t`lunch_start` text DEFAULT '12:00' NOT NULL,\n\t`lunch_min` integer DEFAULT 30 NOT NULL,\n\t`deep_work_before` text DEFAULT '12:00' NOT NULL,\n\t`target_calendar_id` text,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')) NOT NULL\n);",
      "CREATE TABLE `tasks` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`title` text NOT NULL,\n\t`notes` text,\n\t`horizon_id` integer,\n\t`estimate_min` integer DEFAULT 60 NOT NULL,\n\t`priority` integer DEFAULT 3 NOT NULL,\n\t`energy` text DEFAULT 'deep' NOT NULL,\n\t`due_date` text,\n\t`status` text DEFAULT 'backlog' NOT NULL,\n\t`sort_order` integer DEFAULT 0 NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')) NOT NULL,\n\t`completed_at` text\n);",
      "CREATE INDEX `tasks_status_idx` ON `tasks` (`status`);",
      "CREATE INDEX `tasks_horizon_idx` ON `tasks` (`horizon_id`);",
    ],
  },
  {
    name: "0001_connected_goals.sql",
    statements: [
      "CREATE TABLE `block_segments` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`block_id` integer NOT NULL,\n\t`task_id` integer NOT NULL,\n\t`minutes` integer NOT NULL,\n\t`sort_order` integer DEFAULT 0 NOT NULL,\n\t`done_at` text\n);",
      "CREATE INDEX `block_segments_block_idx` ON `block_segments` (`block_id`);",
      "CREATE INDEX `block_segments_task_idx` ON `block_segments` (`task_id`);",
      "CREATE TABLE `time_windows` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`name` text NOT NULL,\n\t`start_time` text NOT NULL,\n\t`end_time` text NOT NULL,\n\t`weekdays` text DEFAULT '1,2,3,4,5' NOT NULL,\n\t`sort_order` integer DEFAULT 0 NOT NULL\n);",
      "DROP INDEX `blocks_task_idx`;",
      "ALTER TABLE `blocks` ADD `window_id` integer;",
      "PRAGMA foreign_keys=OFF;",
      "CREATE TABLE `__new_settings` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`timezone` text DEFAULT 'Europe/Vienna' NOT NULL,\n\t`day_start` text DEFAULT '06:00' NOT NULL,\n\t`day_end` text DEFAULT '18:00' NOT NULL,\n\t`buffer_min` integer DEFAULT 15 NOT NULL,\n\t`max_focus_block_min` integer DEFAULT 60 NOT NULL,\n\t`min_block_min` integer DEFAULT 30 NOT NULL,\n\t`lunch_start` text DEFAULT '12:00' NOT NULL,\n\t`lunch_min` integer DEFAULT 30 NOT NULL,\n\t`deep_work_before` text DEFAULT '12:00' NOT NULL,\n\t`default_window_id` integer,\n\t`target_calendar_id` text,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')) NOT NULL\n);",
      "INSERT INTO `__new_settings`(\"id\", \"timezone\", \"day_start\", \"day_end\", \"buffer_min\", \"max_focus_block_min\", \"min_block_min\", \"lunch_start\", \"lunch_min\", \"deep_work_before\", \"target_calendar_id\", \"updated_at\") SELECT \"id\", \"timezone\", \"day_start\", \"day_end\", \"buffer_min\", \"max_focus_block_min\", \"min_block_min\", \"lunch_start\", \"lunch_min\", \"deep_work_before\", \"target_calendar_id\", \"updated_at\" FROM `settings`;",
      "DROP TABLE `settings`;",
      "ALTER TABLE `__new_settings` RENAME TO `settings`;",
      "PRAGMA foreign_keys=ON;",
      "ALTER TABLE `horizons` ADD `window_id` integer;",
      "ALTER TABLE `tasks` ADD `window_id` integer;;",
      "-- Hand-written data steps (not generated by drizzle-kit) ------------------------\n-- Seed the two windows from the v0.2 brief: learning before lunch, work after.\nINSERT INTO `time_windows` (`name`, `start_time`, `end_time`, `weekdays`, `sort_order`) VALUES ('Learning', '10:30', '14:00', '1,2,3,4,5', 0);",
      "INSERT INTO `time_windows` (`name`, `start_time`, `end_time`, `weekdays`, `sort_order`) VALUES ('Work', '14:00', '17:30', '1,2,3,4,5', 1);",
      "-- Blocks become 30-60 min calendar windows; unassigned work goes to Work.\nUPDATE `settings` SET `max_focus_block_min` = 60, `default_window_id` = (SELECT `id` FROM `time_windows` WHERE `name` = 'Work');",
      "-- Every existing block becomes a single-segment block, so nothing planned is lost\n-- when 0002 drops blocks.task_id.\nINSERT INTO `block_segments` (`block_id`, `task_id`, `minutes`, `sort_order`, `done_at`)\n  SELECT `id`, `task_id`, CAST(ROUND((julianday(`ends_at`) - julianday(`starts_at`)) * 1440) AS INTEGER), 0,\n         CASE WHEN `state` = 'done' THEN `updated_at` END\n  FROM `blocks`;",
      "-- Tasks now keep their sequence within a priority; existing ones keep creation order.\nUPDATE `tasks` SET `sort_order` = `id` WHERE `sort_order` = 0;",
    ],
  },
  {
    name: "0002_drop_legacy_columns.sql",
    statements: [
      "ALTER TABLE `blocks` DROP COLUMN `task_id`;",
      "ALTER TABLE `settings` DROP COLUMN `deep_work_before`;",
    ],
  },
  {
    name: "0003_calendar_view.sql",
    statements: [
      "ALTER TABLE `settings` ADD `calendar_start` text DEFAULT '05:00' NOT NULL;",
      "ALTER TABLE `settings` ADD `calendar_end` text DEFAULT '00:00' NOT NULL;",
      "ALTER TABLE `settings` ADD `calendar_view` text DEFAULT 'day' NOT NULL;",
      "ALTER TABLE `settings` ADD `calendar_filters` text DEFAULT '{}' NOT NULL;",
    ],
  },
  {
    name: "0004_pinned_blocks.sql",
    statements: [
      "ALTER TABLE `blocks` ADD `pinned` integer DEFAULT false NOT NULL;",
    ],
  },
  {
    name: "0005_window_colors.sql",
    statements: [
      "PRAGMA foreign_keys=OFF;",
      "CREATE TABLE `__new_settings` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`timezone` text DEFAULT 'Europe/Vienna' NOT NULL,\n\t`day_start` text DEFAULT '06:00' NOT NULL,\n\t`day_end` text DEFAULT '18:00' NOT NULL,\n\t`buffer_min` integer DEFAULT 15 NOT NULL,\n\t`max_focus_block_min` integer DEFAULT 60 NOT NULL,\n\t`min_block_min` integer DEFAULT 30 NOT NULL,\n\t`lunch_start` text DEFAULT '12:00' NOT NULL,\n\t`lunch_min` integer DEFAULT 30 NOT NULL,\n\t`default_window_id` integer,\n\t`target_calendar_id` text,\n\t`calendar_start` text DEFAULT '05:00' NOT NULL,\n\t`calendar_end` text DEFAULT '00:00' NOT NULL,\n\t`calendar_view` text DEFAULT 'week' NOT NULL,\n\t`calendar_filters` text DEFAULT '{}' NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')) NOT NULL\n);",
      "INSERT INTO `__new_settings`(\"id\", \"timezone\", \"day_start\", \"day_end\", \"buffer_min\", \"max_focus_block_min\", \"min_block_min\", \"lunch_start\", \"lunch_min\", \"default_window_id\", \"target_calendar_id\", \"calendar_start\", \"calendar_end\", \"calendar_view\", \"calendar_filters\", \"updated_at\") SELECT \"id\", \"timezone\", \"day_start\", \"day_end\", \"buffer_min\", \"max_focus_block_min\", \"min_block_min\", \"lunch_start\", \"lunch_min\", \"default_window_id\", \"target_calendar_id\", \"calendar_start\", \"calendar_end\", \"calendar_view\", \"calendar_filters\", \"updated_at\" FROM `settings`;",
      "DROP TABLE `settings`;",
      "ALTER TABLE `__new_settings` RENAME TO `settings`;",
      "PRAGMA foreign_keys=ON;",
      "ALTER TABLE `time_windows` ADD `color` text;",
      "-- Hand-written data steps (not generated by drizzle-kit) ------------------------\n-- The Calendar now opens in Week. A calendar still on the old default (Today) follows;\n-- any other view someone chose in Settings is kept.\nUPDATE `settings` SET `calendar_view` = 'week' WHERE `calendar_view` = 'day';",
    ],
  },
  {
    name: "0006_event_marks.sql",
    statements: [
      "CREATE TABLE `event_marks` (\n\t`key` text PRIMARY KEY NOT NULL,\n\t`title` text DEFAULT '' NOT NULL,\n\t`important` integer DEFAULT false NOT NULL,\n\t`placeholder` integer DEFAULT false NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')) NOT NULL\n);",
    ],
  },
  {
    name: "0007_vacations.sql",
    statements: [
      "CREATE TABLE `vacations` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`starts_at` text NOT NULL,\n\t`ends_at` text NOT NULL,\n\t`windows` text DEFAULT '' NOT NULL,\n\t`note` text,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')) NOT NULL\n);",
      "CREATE INDEX `vacations_range_idx` ON `vacations` (`starts_at`,`ends_at`);",
    ],
  },
  {
    name: "0008_vacation_in_google.sql",
    statements: [
      "ALTER TABLE `vacations` ADD `in_google` integer DEFAULT false NOT NULL;",
      "ALTER TABLE `vacations` ADD `google_event_id` text;",
    ],
  },
  {
    name: "0009_multi_day_classification.sql",
    statements: [
      "ALTER TABLE `event_marks` ADD `not_vacation` integer DEFAULT false NOT NULL;",
      "ALTER TABLE `vacations` ADD `source_event` text;",
    ],
  },
  {
    name: "0010_sequential_tasks.sql",
    statements: [
      "ALTER TABLE `tasks` ADD `sequential` integer DEFAULT false NOT NULL;",
    ],
  },
];
